### ISSUE TITLE
Compatible with Particle Core?

### ISSUE THREAD

**Issue by UnKZero** [MoePus/Flerovium#9]
Is it?

**Comment by MoePus** [comment]
Probably not
I just took a brief look at the source code of Particle core
We have roughly 3 consistent core optimization points
1. light cache
2. frustum culling optimization
3. faster geometry build
In addition, Particle core will also reduce the generation of particles

Since optimization 1 and optimization 2 are repeated, Flerovium and Particle core should be incompatible
At the same time, Particle core cannot perform optimization 3 when Sodium is installed. I guess Flerovium has better performance (untested)

**Comment by MoePus** [comment]
Tested just now, with my 16384 cherry particles test case, Particle core performs 820 average fps which is 20% slower than Flerovium(1000+fps)
^&^
